# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JsV3Vz8uhCt6o63bNaczYLIigqubljfd
"""

# ==============================
# VEXOO LABS ASSIGNMENT (ALL-IN-ONE)
# ==============================

import re
from collections import Counter
from difflib import SequenceMatcher

# Optional imports for Part 2
try:
    from datasets import load_dataset
    from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
    HF_AVAILABLE = True
except:
    HF_AVAILABLE = False


# =========================================================
# PART 1: SLIDING WINDOW + KNOWLEDGE PYRAMID
# =========================================================

def sliding_window(text, window_size=1000, overlap=200):
    chunks = []
    i = 0
    while i < len(text):
        chunk = text[i:i + window_size]
        chunks.append(chunk)
        i += (window_size - overlap)
    return chunks


def summarize(text):
    sentences = text.split(".")
    return ".".join(sentences[:2])


def categorize(text):
    text = text.lower()
    if "price" in text or "cost" in text:
        return "Finance"
    elif "model" in text or "ai" in text:
        return "Technology"
    elif "law" in text:
        return "Legal"
    else:
        return "General"


def extract_keywords(text, top_n=5):
    words = re.findall(r'\w+', text.lower())
    common = Counter(words).most_common(top_n)
    return [word for word, _ in common]


def build_pyramid(chunks):
    pyramid = []

    for chunk in chunks:
        pyramid.append({
            "raw": chunk,
            "summary": summarize(chunk),
            "category": categorize(chunk),
            "keywords": extract_keywords(chunk)
        })

    return pyramid


def similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()


def retrieve(query, pyramid):
    best_score = 0
    best_result = None
    best_layer = None

    for item in pyramid:
        for key in ["raw", "summary", "category", "keywords"]:
            value = str(item[key])
            score = similarity(query.lower(), value.lower())

            if score > best_score:
                best_score = score
                best_result = value
                best_layer = key

    return best_result, best_layer, best_score


# =========================================================
# PART 2: GSM8K TRAINING (SIMULATED LIGHTWEIGHT VERSION)
# =========================================================

def run_training():
    if not HF_AVAILABLE:
        print("\n⚠️ HuggingFace libraries not installed.")
        print("Run: pip install transformers datasets torch\n")
        return

    print("\n📥 Loading GSM8K dataset...")
    dataset = load_dataset("openai/gsm8k", "main")

    train_data = dataset["train"].select(range(3000))
    test_data = dataset["test"].select(range(1000))

    model_name = "distilgpt2"  # lightweight substitute

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token

    def tokenize(example):
        return tokenizer(
            example["question"] + " " + example["answer"],
            truncation=True,
            padding="max_length",
            max_length=128
        )

    print("🔄 Tokenizing...")
    train_data = train_data.map(tokenize, batched=True)
    test_data = test_data.map(tokenize, batched=True)

    print("🤖 Loading model...")
    model = AutoModelForCausalLM.from_pretrained(model_name)

    training_args = TrainingArguments(
        output_dir="./results",
        per_device_train_batch_size=4,
        num_train_epochs=1,
        logging_steps=50,
        save_steps=500,
        evaluation_strategy="epoch"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=test_data
    )

    print("\n🚀 Training started...")
    trainer.train()

    print("\n📊 Evaluating...")
    results = trainer.evaluate()
    print("Evaluation Results:", results)


# =========================================================
# BONUS: REASONING-AWARE ROUTER
# =========================================================

def classify_query(query):
    query = query.lower()

    if any(word in query for word in ["calculate", "solve", "math", "number"]):
        return "math"
    elif any(word in query for word in ["law", "legal", "act"]):
        return "legal"
    else:
        return "general"


def reasoning_router(query, pyramid):
    qtype = classify_query(query)

    if qtype == "math":
        return "🔢 Routed to Math Engine (simulated)", qtype

    elif qtype == "legal":
        return "⚖️ Routed to Legal Rule System (simulated)", qtype

    else:
        result, layer, score = retrieve(query, pyramid)
        return f"📚 Retrieved from {layer}: {result}", qtype


# =========================================================
# MAIN EXECUTION
# =========================================================

def main():
    print("\n==============================")
    print(" VEXOO LABS ASSIGNMENT RUNNER ")
    print("==============================")

    # -----------------------------
    # Load Document
    # -----------------------------
    try:
        with open("sample.txt", "r", encoding="utf-8") as f:
            text = f.read()
    except:
        print("\n⚠️ sample.txt not found. Using default text.\n")
        text = """Artificial Intelligence is transforming industries.
        The cost of AI models is decreasing rapidly.
        Legal frameworks are evolving to regulate AI systems."""

    # -----------------------------
    # Part 1 Execution
    # -----------------------------
    print("\n📄 Running Part 1: Knowledge Pyramid...")

    chunks = sliding_window(text)
    pyramid = build_pyramid(chunks)

    print(f"✅ Created {len(pyramid)} pyramid entries")

    # Query loop
    while True:
        query = input("\nEnter query (or 'exit'): ")

        if query.lower() == "exit":
            break

        response, qtype = reasoning_router(query, pyramid)
        print("\nResponse:", response)
        print("Query Type:", qtype)

    # -----------------------------
    # Part 2 Execution
    # -----------------------------
    choice = input("\nRun Part 2 Training? (yes/no): ")

    if choice.lower() == "yes":
        run_training()


# =========================================================

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')